[workspace]
members = [
    "engine",
    "conversion",
    "visualization",
    "utils",
    "catchup",
    "chpot",
    "tdpot",
    "cchpp",
    "fastdta",
]
resolver = "2"

[profile.dev]
opt-level = 0
[profile.release]
debug = true
incremental = false
codegen-units = 1
